// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct AlgSimp
{
	struct AlgSimp_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct Doit
{
	struct Doit_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
// vtables structures
struct AlgSimp_vtable
{
	char * AlgSimp_gc_map;
};

struct Doit_vtable
{
	char * Doit_gc_map;
	int (*Doit_doit)();
};


// vtables defines
struct AlgSimp_vtable AlgSimp_vtable_ ;
struct Doit_vtable Doit_vtable_ ;

// methods
void * frame_prev;

struct Doit_doit_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Doit_doit(struct Doit * this)
{
	int x;
	int x_1;
	int x_2;

	char * Doit_doit_arguments_gc_map = "1";
	char * Doit_doit_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Doit_doit_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Doit_doit_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Doit_doit_locals_gc_map;

L_0:
	System_out_println (0);

	frame_prev = frame.frame_prev;
	return 0;
}

// vtables
struct AlgSimp_vtable AlgSimp_vtable_ = 
{
	"",
};

struct Doit_vtable Doit_vtable_ = 
{
	"",
	Doit_doit,
};


// main method

struct Tiger_main_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Doit * x_0;
	struct Doit * x_4;
};

int Tiger_main ()
{
	int x_3;
	char * tiger_main_arguments_gc_map = "";
	char * tiger_main_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tiger_main_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = tiger_main_arguments_gc_map;
	frame.locals_gc_map = tiger_main_locals_gc_map;

L_1:
	frame.x_4 = ((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit))));
	x_3 = frame.x_4->vptr->Doit_doit(frame.x_4);
	System_out_println (x_3);

	frame_prev = frame.frame_prev;
	return 0;
}




