// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct BinaryTree
{
	struct BinaryTree_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct BT
{
	struct BT_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct Tree
{
	struct Tree_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
	struct Tree * left;
	struct Tree * right;
	int key;
	int has_left;
	int has_right;
	struct Tree * my_null;
};
// vtables structures
struct BinaryTree_vtable
{
	char * BinaryTree_gc_map;
};

struct BT_vtable
{
	char * BT_gc_map;
	int (*BT_Start)();
};

struct Tree_vtable
{
	char * Tree_gc_map;
	int (*Tree_Init)();
	int (*Tree_SetRight)();
	int (*Tree_SetLeft)();
	struct Tree * (*Tree_GetRight)();
	struct Tree * (*Tree_GetLeft)();
	int (*Tree_GetKey)();
	int (*Tree_SetKey)();
	int (*Tree_GetHas_Right)();
	int (*Tree_GetHas_Left)();
	int (*Tree_SetHas_Left)();
	int (*Tree_SetHas_Right)();
	int (*Tree_Compare)();
	int (*Tree_Insert)();
	int (*Tree_Delete)();
	int (*Tree_Remove)();
	int (*Tree_RemoveRight)();
	int (*Tree_RemoveLeft)();
	int (*Tree_Search)();
	int (*Tree_Print)();
	int (*Tree_RecPrint)();
};


// vtables defines
struct BinaryTree_vtable BinaryTree_vtable_ ;
struct BT_vtable BT_vtable_ ;
struct Tree_vtable Tree_vtable_ ;

// methods
void * frame_prev;

struct BT_Start_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * root;
	struct Tree * x_1;
	struct Tree * x_2;
	struct Tree * x_3;
	struct Tree * x_4;
	struct Tree * x_5;
	struct Tree * x_6;
	struct Tree * x_7;
	struct Tree * x_8;
	struct Tree * x_9;
	struct Tree * x_10;
	struct Tree * x_11;
	struct Tree * x_12;
	struct Tree * x_13;
	struct Tree * x_14;
	struct Tree * x_15;
	struct Tree * x_16;
	struct Tree * x_17;
	struct Tree * x_18;
	struct Tree * x_19;
	struct Tree * x_78;
};

int BT_Start(struct BT * this)
{
	int ntb;
	int x_79;
	int x_80;
	int x_81;
	int x_82;
	int x_83;
	int x_84;
	int x_85;
	int x_86;
	int x_87;
	int x_88;
	int x_89;
	int x_90;
	int x_91;
	int x_92;
	int x_93;
	int x_94;
	int x_95;
	int x_96;
	int x_97;

	char * BT_Start_arguments_gc_map = "1";
	char * BT_Start_locals_gc_map = "111111111111111111111";
	//put the GC stack frame onto the call stack.
	struct BT_Start_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BT_Start_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BT_Start_locals_gc_map;

L_0:
	frame.x_78 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.root = frame.x_78;
	x_79 = frame.root->vptr->Tree_Init(frame.root, 16);
	x_80 = frame.root->vptr->Tree_Print(frame.root);
	System_out_println (100000000);

	x_81 = frame.root->vptr->Tree_Insert(frame.root, 8);
	x_82 = frame.root->vptr->Tree_Print(frame.root);
	x_83 = frame.root->vptr->Tree_Insert(frame.root, 24);
	x_84 = frame.root->vptr->Tree_Insert(frame.root, 4);
	x_85 = frame.root->vptr->Tree_Insert(frame.root, 12);
	x_86 = frame.root->vptr->Tree_Insert(frame.root, 20);
	x_87 = frame.root->vptr->Tree_Insert(frame.root, 28);
	x_88 = frame.root->vptr->Tree_Insert(frame.root, 14);
	x_89 = frame.root->vptr->Tree_Print(frame.root);
	x_90 = frame.root->vptr->Tree_Search(frame.root, 24);
	System_out_println (x_90);

	x_91 = frame.root->vptr->Tree_Search(frame.root, 12);
	System_out_println (x_91);

	x_92 = frame.root->vptr->Tree_Search(frame.root, 16);
	System_out_println (x_92);

	x_93 = frame.root->vptr->Tree_Search(frame.root, 50);
	System_out_println (x_93);

	x_94 = frame.root->vptr->Tree_Search(frame.root, 12);
	System_out_println (x_94);

	x_95 = frame.root->vptr->Tree_Delete(frame.root, 12);
	x_96 = frame.root->vptr->Tree_Print(frame.root);
	x_97 = frame.root->vptr->Tree_Search(frame.root, 12);
	System_out_println (x_97);

	frame_prev = frame.frame_prev;
	return 0;
}

struct Tree_Init_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_Init(struct Tree * this, int v_key)
{

	char * Tree_Init_arguments_gc_map = "10";
	char * Tree_Init_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_Init_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Init_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Init_locals_gc_map;

L_1:

	this->key = v_key;
	this->has_left = 0;
	this->has_right = 0;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_SetRight_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetRight(struct Tree * this, struct Tree * rn)
{

	char * Tree_SetRight_arguments_gc_map = "11";
	char * Tree_SetRight_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetRight_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetRight_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetRight_locals_gc_map;

L_2:

	this->right = rn;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_SetLeft_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_98;
	struct Tree * x_99;
	struct Tree * x_100;
	struct Tree * x_101;
	struct Tree * x_102;
	struct Tree * x_103;
	struct Tree * x_104;
	struct Tree * x_105;
};

int Tree_SetLeft(struct Tree * this, struct Tree * ln)
{

	char * Tree_SetLeft_arguments_gc_map = "11";
	char * Tree_SetLeft_locals_gc_map = "11111111";
	//put the GC stack frame onto the call stack.
	struct Tree_SetLeft_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetLeft_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetLeft_locals_gc_map;

L_3:

	frame.x_98 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_98;
	frame.x_99 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_99;
	frame.x_100 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_100;
	frame.x_101 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_101;
	frame.x_102 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_102;
	frame.x_103 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_103;
	frame.x_104 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_104;
	frame.x_105 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	this->left = frame.x_105;
	this->left = ln;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_GetRight_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

struct Tree * Tree_GetRight(struct Tree * this)
{

	char * Tree_GetRight_arguments_gc_map = "1";
	char * Tree_GetRight_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetRight_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetRight_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetRight_locals_gc_map;

L_4:
	frame_prev = frame.frame_prev;
	return this->right;
}

struct Tree_GetLeft_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

struct Tree * Tree_GetLeft(struct Tree * this)
{

	char * Tree_GetLeft_arguments_gc_map = "1";
	char * Tree_GetLeft_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetLeft_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetLeft_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetLeft_locals_gc_map;

L_5:
	frame_prev = frame.frame_prev;
	return this->left;
}

struct Tree_GetKey_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_GetKey(struct Tree * this)
{

	char * Tree_GetKey_arguments_gc_map = "1";
	char * Tree_GetKey_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetKey_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetKey_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetKey_locals_gc_map;

L_6:
	frame_prev = frame.frame_prev;
	return this->key;
}

struct Tree_SetKey_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetKey(struct Tree * this, int v_key)
{

	char * Tree_SetKey_arguments_gc_map = "10";
	char * Tree_SetKey_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetKey_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetKey_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetKey_locals_gc_map;

L_7:

	this->key = v_key;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_GetHas_Right_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_GetHas_Right(struct Tree * this)
{

	char * Tree_GetHas_Right_arguments_gc_map = "1";
	char * Tree_GetHas_Right_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetHas_Right_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetHas_Right_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetHas_Right_locals_gc_map;

L_8:
	frame_prev = frame.frame_prev;
	return this->has_right;
}

struct Tree_GetHas_Left_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_GetHas_Left(struct Tree * this)
{

	char * Tree_GetHas_Left_arguments_gc_map = "1";
	char * Tree_GetHas_Left_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetHas_Left_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetHas_Left_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetHas_Left_locals_gc_map;

L_9:
	frame_prev = frame.frame_prev;
	return this->has_left;
}

struct Tree_SetHas_Left_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetHas_Left(struct Tree * this, int val)
{

	char * Tree_SetHas_Left_arguments_gc_map = "10";
	char * Tree_SetHas_Left_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetHas_Left_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetHas_Left_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetHas_Left_locals_gc_map;

L_10:

	this->has_left = val;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_SetHas_Right_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetHas_Right(struct Tree * this, int val)
{

	char * Tree_SetHas_Right_arguments_gc_map = "10";
	char * Tree_SetHas_Right_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetHas_Right_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetHas_Right_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetHas_Right_locals_gc_map;

L_11:

	this->has_right = val;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_Compare_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_Compare(struct Tree * this, int num1, int num2)
{
	int ntb;
	int nti;
	int x_106;
	int x_107;
	int x_108;

	char * Tree_Compare_arguments_gc_map = "100";
	char * Tree_Compare_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_Compare_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Compare_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Compare_locals_gc_map;

L_12:


	x_106 = num2 + 1;
	nti = x_106;
	x_107 = num1 < num2;
	if (x_107)
	  goto L_13;
	else
	  goto L_14;
L_13:
	ntb = 0;
	goto L_15;
L_14:
	x_108 = num1 < nti;
	if (!x_108)
	  goto L_16;
	else
	  goto L_17;
L_16:
	ntb = 0;
	goto L_18;
L_17:
	ntb = 1;
	goto L_18;
L_18:
	goto L_15;
L_15:
	frame_prev = frame.frame_prev;
	return ntb;
}

struct Tree_Insert_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * new_node;
	struct Tree * current_node;
	struct Tree * x_20;
	struct Tree * x_21;
	struct Tree * x_22;
	struct Tree * x_23;
	struct Tree * x_24;
	struct Tree * x_25;
	struct Tree * x_26;
	struct Tree * x_27;
	struct Tree * x_28;
	struct Tree * x_29;
	struct Tree * x_109;
	struct Tree * x_114;
	struct Tree * x_118;
};

int Tree_Insert(struct Tree * this, int v_key)
{
	int ntb;
	int cont;
	int key_aux;
	int x_110;
	int x_111;
	int x_112;
	int x_113;
	int x_115;
	int x_116;
	int x_117;
	int x_119;
	int x_120;

	char * Tree_Insert_arguments_gc_map = "10";
	char * Tree_Insert_locals_gc_map = "111111111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Insert_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Insert_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Insert_locals_gc_map;

L_19:


	frame.x_109 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.new_node = frame.x_109;
	x_110 = frame.new_node->vptr->Tree_Init(frame.new_node, v_key);
	frame.current_node = this;
	cont = 1;
	goto L_22;
L_22:
	if (cont)
	  goto L_20;
	else
	  goto L_21;
L_20:
	x_111 = frame.current_node->vptr->Tree_GetKey(frame.current_node);
	key_aux = x_111;
	x_112 = v_key < key_aux;
	if (x_112)
	  goto L_23;
	else
	  goto L_24;
L_23:
	x_113 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	if (x_113)
	  goto L_26;
	else
	  goto L_27;
L_26:
	frame.x_114 = frame.current_node->vptr->Tree_GetLeft(frame.current_node);
	frame.current_node = frame.x_114;
	goto L_28;
L_27:
	cont = 0;
	x_115 = frame.current_node->vptr->Tree_SetHas_Left(frame.current_node, 1);
	x_116 = frame.current_node->vptr->Tree_SetLeft(frame.current_node, frame.new_node);
	goto L_28;
L_28:
	goto L_25;
L_24:
	x_117 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	if (x_117)
	  goto L_29;
	else
	  goto L_30;
L_29:
	frame.x_118 = frame.current_node->vptr->Tree_GetRight(frame.current_node);
	frame.current_node = frame.x_118;
	goto L_31;
L_30:
	cont = 0;
	x_119 = frame.current_node->vptr->Tree_SetHas_Right(frame.current_node, 1);
	x_120 = frame.current_node->vptr->Tree_SetRight(frame.current_node, frame.new_node);
	goto L_31;
L_31:
	goto L_25;
L_25:
	goto L_22;
L_21:
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_Delete_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * current_node;
	struct Tree * parent_node;
	struct Tree * x_30;
	struct Tree * x_31;
	struct Tree * x_32;
	struct Tree * x_33;
	struct Tree * x_34;
	struct Tree * x_35;
	struct Tree * x_36;
	struct Tree * x_37;
	struct Tree * x_38;
	struct Tree * x_124;
	struct Tree * x_127;
};

int Tree_Delete(struct Tree * this, int v_key)
{
	int cont;
	int found;
	int is_root;
	int key_aux;
	int ntb;
	int x_121;
	int x_122;
	int x_123;
	int x_125;
	int x_126;
	int x_128;
	int x_129;
	int x_130;
	int x_131;
	int x_132;

	char * Tree_Delete_arguments_gc_map = "10";
	char * Tree_Delete_locals_gc_map = "1111111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Delete_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Delete_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Delete_locals_gc_map;

L_32:


	frame.current_node = this;
	frame.parent_node = this;
	cont = 1;
	found = 0;
	is_root = 1;
	goto L_35;
L_35:
	if (cont)
	  goto L_33;
	else
	  goto L_34;
L_33:
	x_121 = frame.current_node->vptr->Tree_GetKey(frame.current_node);
	key_aux = x_121;
	x_122 = v_key < key_aux;
	if (x_122)
	  goto L_36;
	else
	  goto L_37;
L_36:
	x_123 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	if (x_123)
	  goto L_39;
	else
	  goto L_40;
L_39:
	frame.parent_node = frame.current_node;
	frame.x_124 = frame.current_node->vptr->Tree_GetLeft(frame.current_node);
	frame.current_node = frame.x_124;
	goto L_41;
L_40:
	cont = 0;
	goto L_41;
L_41:
	goto L_38;
L_37:
	x_125 = key_aux < v_key;
	if (x_125)
	  goto L_42;
	else
	  goto L_43;
L_42:
	x_126 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	if (x_126)
	  goto L_45;
	else
	  goto L_46;
L_45:
	frame.parent_node = frame.current_node;
	frame.x_127 = frame.current_node->vptr->Tree_GetRight(frame.current_node);
	frame.current_node = frame.x_127;
	goto L_47;
L_46:
	cont = 0;
	goto L_47;
L_47:
	goto L_44;
L_43:
	if (is_root)
	  goto L_48;
	else
	  goto L_49;
L_48:
	x_129 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	x_130 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	x_128 = !x_129 && !x_130;
	if (x_128)
	  goto L_51;
	else
	  goto L_52;
L_51:
	goto L_53;
L_52:
	x_131 = this->vptr->Tree_Remove(this, frame.parent_node, frame.current_node);
	goto L_53;
L_53:
	goto L_50;
L_49:
	x_132 = this->vptr->Tree_Remove(this, frame.parent_node, frame.current_node);
	goto L_50;
L_50:
	found = 1;
	cont = 0;
	goto L_44;
L_44:
	goto L_38;
L_38:
	is_root = 0;
	goto L_35;
L_34:
	frame_prev = frame.frame_prev;
	return found;
}

struct Tree_Remove_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_39;
	struct Tree * x_40;
	struct Tree * x_41;
	struct Tree * x_42;
	struct Tree * x_43;
	struct Tree * x_44;
	struct Tree * x_45;
	struct Tree * x_46;
	struct Tree * x_47;
	struct Tree * x_48;
	struct Tree * x_49;
	struct Tree * x_50;
	struct Tree * x_139;
};

int Tree_Remove(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
	int ntb;
	int auxkey1;
	int auxkey2;
	int x_133;
	int x_134;
	int x_135;
	int x_136;
	int x_137;
	int x_138;
	int x_140;
	int x_141;
	int x_142;
	int x_143;
	int x_144;

	char * Tree_Remove_arguments_gc_map = "111";
	char * Tree_Remove_locals_gc_map = "1111111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Remove_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Remove_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Remove_locals_gc_map;

L_54:



	x_133 = c_node->vptr->Tree_GetHas_Left(c_node);
	if (x_133)
	  goto L_55;
	else
	  goto L_56;
L_55:
	x_134 = this->vptr->Tree_RemoveLeft(this, p_node, c_node);
	goto L_57;
L_56:
	x_135 = c_node->vptr->Tree_GetHas_Right(c_node);
	if (x_135)
	  goto L_58;
	else
	  goto L_59;
L_58:
	x_136 = this->vptr->Tree_RemoveRight(this, p_node, c_node);
	goto L_60;
L_59:
	x_137 = c_node->vptr->Tree_GetKey(c_node);
	auxkey1 = x_137;
	frame.x_139 = p_node->vptr->Tree_GetLeft(p_node);
	x_138 = frame.x_139->vptr->Tree_GetKey(frame.x_139);
	auxkey2 = x_138;
	x_140 = this->vptr->Tree_Compare(this, auxkey1, auxkey2);
	if (x_140)
	  goto L_61;
	else
	  goto L_62;
L_61:
	x_141 = p_node->vptr->Tree_SetLeft(p_node, this->my_null);
	x_142 = p_node->vptr->Tree_SetHas_Left(p_node, 0);
	goto L_63;
L_62:
	x_143 = p_node->vptr->Tree_SetRight(p_node, this->my_null);
	x_144 = p_node->vptr->Tree_SetHas_Right(p_node, 0);
	goto L_63;
L_63:
	goto L_60;
L_60:
	goto L_57;
L_57:
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_RemoveRight_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_51;
	struct Tree * x_52;
	struct Tree * x_53;
	struct Tree * x_54;
	struct Tree * x_55;
	struct Tree * x_56;
	struct Tree * x_57;
	struct Tree * x_148;
	struct Tree * x_149;
};

int Tree_RemoveRight(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
	int ntb;
	int x_145;
	int x_146;
	int x_147;
	int x_150;
	int x_151;

	char * Tree_RemoveRight_arguments_gc_map = "111";
	char * Tree_RemoveRight_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_RemoveRight_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_RemoveRight_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_RemoveRight_locals_gc_map;

L_64:


	goto L_67;
L_67:
	x_145 = c_node->vptr->Tree_GetHas_Right(c_node);
	if (x_145)
	  goto L_65;
	else
	  goto L_66;
L_65:
	frame.x_148 = c_node->vptr->Tree_GetRight(c_node);
	x_147 = frame.x_148->vptr->Tree_GetKey(frame.x_148);
	x_146 = c_node->vptr->Tree_SetKey(c_node, x_147);
	p_node = c_node;
	frame.x_149 = c_node->vptr->Tree_GetRight(c_node);
	c_node = frame.x_149;
	goto L_67;
L_66:
	x_150 = p_node->vptr->Tree_SetRight(p_node, this->my_null);
	x_151 = p_node->vptr->Tree_SetHas_Right(p_node, 0);
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_RemoveLeft_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_58;
	struct Tree * x_59;
	struct Tree * x_60;
	struct Tree * x_61;
	struct Tree * x_62;
	struct Tree * x_63;
	struct Tree * x_64;
	struct Tree * x_155;
	struct Tree * x_156;
};

int Tree_RemoveLeft(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
	int ntb;
	int x_152;
	int x_153;
	int x_154;
	int x_157;
	int x_158;

	char * Tree_RemoveLeft_arguments_gc_map = "111";
	char * Tree_RemoveLeft_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_RemoveLeft_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_RemoveLeft_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_RemoveLeft_locals_gc_map;

L_68:


	goto L_71;
L_71:
	x_152 = c_node->vptr->Tree_GetHas_Left(c_node);
	if (x_152)
	  goto L_69;
	else
	  goto L_70;
L_69:
	frame.x_155 = c_node->vptr->Tree_GetLeft(c_node);
	x_154 = frame.x_155->vptr->Tree_GetKey(frame.x_155);
	x_153 = c_node->vptr->Tree_SetKey(c_node, x_154);
	p_node = c_node;
	frame.x_156 = c_node->vptr->Tree_GetLeft(c_node);
	c_node = frame.x_156;
	goto L_71;
L_70:
	x_157 = p_node->vptr->Tree_SetLeft(p_node, this->my_null);
	x_158 = p_node->vptr->Tree_SetHas_Left(p_node, 0);
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_Search_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * current_node;
	struct Tree * x_65;
	struct Tree * x_66;
	struct Tree * x_67;
	struct Tree * x_68;
	struct Tree * x_69;
	struct Tree * x_162;
	struct Tree * x_165;
};

int Tree_Search(struct Tree * this, int v_key)
{
	int cont;
	int ifound;
	int key_aux;
	int x_159;
	int x_160;
	int x_161;
	int x_163;
	int x_164;

	char * Tree_Search_arguments_gc_map = "10";
	char * Tree_Search_locals_gc_map = "11111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Search_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Search_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Search_locals_gc_map;

L_72:


	frame.current_node = this;
	cont = 1;
	ifound = 0;
	goto L_75;
L_75:
	if (cont)
	  goto L_73;
	else
	  goto L_74;
L_73:
	x_159 = frame.current_node->vptr->Tree_GetKey(frame.current_node);
	key_aux = x_159;
	x_160 = v_key < key_aux;
	if (x_160)
	  goto L_76;
	else
	  goto L_77;
L_76:
	x_161 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	if (x_161)
	  goto L_79;
	else
	  goto L_80;
L_79:
	frame.x_162 = frame.current_node->vptr->Tree_GetLeft(frame.current_node);
	frame.current_node = frame.x_162;
	goto L_81;
L_80:
	cont = 0;
	goto L_81;
L_81:
	goto L_78;
L_77:
	x_163 = key_aux < v_key;
	if (x_163)
	  goto L_82;
	else
	  goto L_83;
L_82:
	x_164 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	if (x_164)
	  goto L_85;
	else
	  goto L_86;
L_85:
	frame.x_165 = frame.current_node->vptr->Tree_GetRight(frame.current_node);
	frame.current_node = frame.x_165;
	goto L_87;
L_86:
	cont = 0;
	goto L_87;
L_87:
	goto L_84;
L_83:
	ifound = 1;
	cont = 0;
	goto L_84;
L_84:
	goto L_78;
L_78:
	goto L_75;
L_74:
	frame_prev = frame.frame_prev;
	return ifound;
}

struct Tree_Print_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * current_node;
	struct Tree * x_70;
};

int Tree_Print(struct Tree * this)
{
	int ntb;
	int x_166;

	char * Tree_Print_arguments_gc_map = "1";
	char * Tree_Print_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tree_Print_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Print_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Print_locals_gc_map;

L_88:

	frame.current_node = this;
	x_166 = this->vptr->Tree_RecPrint(this, frame.current_node);
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_RecPrint_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_71;
	struct Tree * x_72;
	struct Tree * x_73;
	struct Tree * x_74;
	struct Tree * x_75;
	struct Tree * x_76;
	struct Tree * x_77;
	struct Tree * x_169;
	struct Tree * x_173;
};

int Tree_RecPrint(struct Tree * this, struct Tree * node)
{
	int ntb;
	int x_167;
	int x_168;
	int x_170;
	int x_171;
	int x_172;

	char * Tree_RecPrint_arguments_gc_map = "11";
	char * Tree_RecPrint_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_RecPrint_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_RecPrint_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_RecPrint_locals_gc_map;

L_89:


	x_167 = node->vptr->Tree_GetHas_Left(node);
	if (x_167)
	  goto L_90;
	else
	  goto L_91;
L_90:
	frame.x_169 = node->vptr->Tree_GetLeft(node);
	x_168 = this->vptr->Tree_RecPrint(this, frame.x_169);
	goto L_92;
L_91:
	goto L_92;
L_92:
	x_170 = node->vptr->Tree_GetKey(node);
	System_out_println (x_170);

	x_171 = node->vptr->Tree_GetHas_Right(node);
	if (x_171)
	  goto L_93;
	else
	  goto L_94;
L_93:
	frame.x_173 = node->vptr->Tree_GetRight(node);
	x_172 = this->vptr->Tree_RecPrint(this, frame.x_173);
	goto L_95;
L_94:
	goto L_95;
L_95:
	frame_prev = frame.frame_prev;
	return 1;
}

// vtables
struct BinaryTree_vtable BinaryTree_vtable_ = 
{
	"",
};

struct BT_vtable BT_vtable_ = 
{
	"",
	BT_Start,
};

struct Tree_vtable Tree_vtable_ = 
{
	"110001",
	Tree_Init,
	Tree_SetRight,
	Tree_SetLeft,
	Tree_GetRight,
	Tree_GetLeft,
	Tree_GetKey,
	Tree_SetKey,
	Tree_GetHas_Right,
	Tree_GetHas_Left,
	Tree_SetHas_Left,
	Tree_SetHas_Right,
	Tree_Compare,
	Tree_Insert,
	Tree_Delete,
	Tree_Remove,
	Tree_RemoveRight,
	Tree_RemoveLeft,
	Tree_Search,
	Tree_Print,
	Tree_RecPrint,
};


// main method

struct Tiger_main_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct BT * x_0;
	struct BT * x_175;
};

int Tiger_main ()
{
	int x_174;
	char * tiger_main_arguments_gc_map = "";
	char * tiger_main_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tiger_main_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = tiger_main_arguments_gc_map;
	frame.locals_gc_map = tiger_main_locals_gc_map;

L_96:
	frame.x_175 = ((struct BT*)(Tiger_new (&BT_vtable_, sizeof(struct BT))));
	x_174 = frame.x_175->vptr->BT_Start(frame.x_175);
	System_out_println (x_174);

	frame_prev = frame.frame_prev;
	return 0;
}




