// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct BubbleSort
{
	struct BubbleSort_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct BBS
{
	struct BBS_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
	int * number;
	int size;
	int a;
};
// vtables structures
struct BubbleSort_vtable
{
	char * BubbleSort_gc_map;
};

struct BBS_vtable
{
	char * BBS_gc_map;
	int (*BBS_Start)();
	int (*BBS_Sort)();
	int (*BBS_Print)();
	int (*BBS_Init)();
};


// vtables defines
struct BubbleSort_vtable BubbleSort_vtable_ ;
struct BBS_vtable BBS_vtable_ ;

// methods
void * frame_prev;

struct BBS_Start_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct BBS * x_1;
	struct BBS * x_2;
	struct BBS * x_3;
	struct BBS * x_4;
};

int BBS_Start(struct BBS * this, int sz)
{
	int aux01;
	int x_5;
	int x_6;
	int x_7;
	int x_8;

	char * BBS_Start_arguments_gc_map = "10";
	char * BBS_Start_locals_gc_map = "1111";
	//put the GC stack frame onto the call stack.
	struct BBS_Start_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BBS_Start_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BBS_Start_locals_gc_map;

L_0:


	x_5 = this->vptr->BBS_Init(this, sz);
	x_6 = this->vptr->BBS_Print(this);
	System_out_println (99999);

	x_7 = this->vptr->BBS_Sort(this);
	x_8 = this->vptr->BBS_Print(this);
	frame_prev = frame.frame_prev;
	return 0;
}

struct BBS_Sort_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int BBS_Sort(struct BBS * this)
{
	int nt;
	int i;
	int aux02;
	int aux04;
	int aux05;
	int aux06;
	int aux07;
	int j;
	int t;
	int x_9;
	int x_10;
	int x_11;
	int x_12;
	int x_13;
	int x_14;
	int x_15;
	int x_16;
	int x_17;

	char * BBS_Sort_arguments_gc_map = "1";
	char * BBS_Sort_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct BBS_Sort_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BBS_Sort_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BBS_Sort_locals_gc_map;

L_1:
	x_9 = this->size - 1;
	i = x_9;
	goto L_4;
L_4:
	x_10 = -1 < i;
	if (x_10)
	  goto L_2;
	else
	  goto L_3;
L_2:
	j = 1;
	goto L_7;
L_7:
	x_12 = i + 1;
	x_11 = j < x_12;
	if (x_11)
	  goto L_5;
	else
	  goto L_6;
L_5:
	x_13 = j - 1;
	aux07 = x_13;
	aux04 = (this->number + 4)[aux07];
	aux05 = (this->number + 4)[j];
	x_14 = aux05 < aux04;
	if (x_14)
	  goto L_8;
	else
	  goto L_9;
L_8:
	x_15 = j - 1;
	aux06 = x_15;
	t = (this->number + 4)[aux06];
	(this->number + 4)[aux06] = (this->number + 4)[j];
	(this->number + 4)[j] = t;
	goto L_10;
L_9:
	goto L_10;
L_10:
	x_16 = j + 1;
	j = x_16;
	goto L_7;
L_6:
	x_17 = i - 1;
	i = x_17;
	goto L_4;
L_3:
	frame_prev = frame.frame_prev;
	return 0;
}

struct BBS_Print_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int BBS_Print(struct BBS * this)
{
	int j;
	int x_18;
	int x_19;

	char * BBS_Print_arguments_gc_map = "1";
	char * BBS_Print_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct BBS_Print_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BBS_Print_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BBS_Print_locals_gc_map;

L_11:
	j = 0;
	goto L_14;
L_14:
	x_18 = j < this->size;
	if (x_18)
	  goto L_12;
	else
	  goto L_13;
L_12:
	System_out_println ((this->number + 4)[j]);

	x_19 = j + 1;
	j = x_19;
	goto L_14;
L_13:
	frame_prev = frame.frame_prev;
	return 0;
}

struct BBS_Init_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	int * x_20;
};

int BBS_Init(struct BBS * this, int sz)
{
	int * x_20;

	char * BBS_Init_arguments_gc_map = "10";
	char * BBS_Init_locals_gc_map = "1";
	//put the GC stack frame onto the call stack.
	struct BBS_Init_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BBS_Init_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BBS_Init_locals_gc_map;

L_15:

	this->size = sz;
	x_20 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_20;
	(this->number + 4)[0] = 20;
	(this->number + 4)[1] = 7;
	(this->number + 4)[2] = 12;
	(this->number + 4)[3] = 18;
	(this->number + 4)[4] = 2;
	(this->number + 4)[5] = 11;
	(this->number + 4)[6] = 6;
	(this->number + 4)[7] = 9;
	(this->number + 4)[8] = 19;
	(this->number + 4)[9] = 5;
	frame_prev = frame.frame_prev;
	return 0;
}

// vtables
struct BubbleSort_vtable BubbleSort_vtable_ = 
{
	"",
};

struct BBS_vtable BBS_vtable_ = 
{
	"100",
	BBS_Start,
	BBS_Sort,
	BBS_Print,
	BBS_Init,
};


// main method

struct Tiger_main_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct BBS * x_0;
	struct BBS * x_22;
};

int Tiger_main ()
{
	int x_21;
	char * tiger_main_arguments_gc_map = "";
	char * tiger_main_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tiger_main_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = tiger_main_arguments_gc_map;
	frame.locals_gc_map = tiger_main_locals_gc_map;

L_16:
	frame.x_22 = ((struct BBS*)(Tiger_new (&BBS_vtable_, sizeof(struct BBS))));
	x_21 = frame.x_22->vptr->BBS_Start(frame.x_22, 10);
	System_out_println (x_21);

	frame_prev = frame.frame_prev;
	return 0;
}




