// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct BinarySearch
{
	struct BinarySearch_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct BS
{
	struct BS_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
	int * number;
	int size;
};
// vtables structures
struct BinarySearch_vtable
{
	char * BinarySearch_gc_map;
};

struct BS_vtable
{
	char * BS_gc_map;
	int (*BS_Start)();
	int (*BS_Search)();
	int (*BS_Div)();
	int (*BS_Compare)();
	int (*BS_Print)();
	int (*BS_Init)();
};


// vtables defines
struct BinarySearch_vtable BinarySearch_vtable_ ;
struct BS_vtable BS_vtable_ ;

// methods
void * frame_prev;

struct BS_Start_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct BS * x_1;
	struct BS * x_2;
	struct BS * x_3;
	struct BS * x_4;
	struct BS * x_5;
	struct BS * x_6;
	struct BS * x_7;
	struct BS * x_8;
	struct BS * x_9;
	struct BS * x_10;
};

int BS_Start(struct BS * this, int sz)
{
	int aux01;
	int aux02;
	int x_14;
	int x_15;
	int x_16;
	int x_17;
	int x_18;
	int x_19;
	int x_20;
	int x_21;
	int x_22;
	int x_23;

	char * BS_Start_arguments_gc_map = "10";
	char * BS_Start_locals_gc_map = "1111111111";
	//put the GC stack frame onto the call stack.
	struct BS_Start_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BS_Start_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BS_Start_locals_gc_map;

L_0:


	x_14 = this->vptr->BS_Init(this, sz);
	x_15 = this->vptr->BS_Print(this);
	x_16 = this->vptr->BS_Search(this, 8);
	if (x_16)
	  goto L_1;
	else
	  goto L_2;
L_1:
	System_out_println (1);

	goto L_3;
L_2:
	System_out_println (0);

	goto L_3;
L_3:
	x_17 = this->vptr->BS_Search(this, 19);
	if (x_17)
	  goto L_4;
	else
	  goto L_5;
L_4:
	System_out_println (1);

	goto L_6;
L_5:
	System_out_println (0);

	goto L_6;
L_6:
	x_18 = this->vptr->BS_Search(this, 20);
	if (x_18)
	  goto L_7;
	else
	  goto L_8;
L_7:
	System_out_println (1);

	goto L_9;
L_8:
	System_out_println (0);

	goto L_9;
L_9:
	x_19 = this->vptr->BS_Search(this, 21);
	if (x_19)
	  goto L_10;
	else
	  goto L_11;
L_10:
	System_out_println (1);

	goto L_12;
L_11:
	System_out_println (0);

	goto L_12;
L_12:
	x_20 = this->vptr->BS_Search(this, 37);
	if (x_20)
	  goto L_13;
	else
	  goto L_14;
L_13:
	System_out_println (1);

	goto L_15;
L_14:
	System_out_println (0);

	goto L_15;
L_15:
	x_21 = this->vptr->BS_Search(this, 38);
	if (x_21)
	  goto L_16;
	else
	  goto L_17;
L_16:
	System_out_println (1);

	goto L_18;
L_17:
	System_out_println (0);

	goto L_18;
L_18:
	x_22 = this->vptr->BS_Search(this, 39);
	if (x_22)
	  goto L_19;
	else
	  goto L_20;
L_19:
	System_out_println (1);

	goto L_21;
L_20:
	System_out_println (0);

	goto L_21;
L_21:
	x_23 = this->vptr->BS_Search(this, 50);
	if (x_23)
	  goto L_22;
	else
	  goto L_23;
L_22:
	System_out_println (1);

	goto L_24;
L_23:
	System_out_println (0);

	goto L_24;
L_24:
	frame_prev = frame.frame_prev;
	return 999;
}

struct BS_Search_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct BS * x_11;
	struct BS * x_12;
	struct BS * x_13;
};

int BS_Search(struct BS * this, int num)
{
	int bs01;
	int right;
	int left;
	int var_cont;
	int medium;
	int aux01;
	int nt;
	int x_24;
	int x_25;
	int x_26;
	int x_27;
	int x_28;
	int x_29;
	int x_30;
	int x_31;
	int x_32;

	char * BS_Search_arguments_gc_map = "10";
	char * BS_Search_locals_gc_map = "111";
	//put the GC stack frame onto the call stack.
	struct BS_Search_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BS_Search_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BS_Search_locals_gc_map;

L_25:


	aux01 = 0;
	right = *(this->number + 2)/4 - 4;
	x_24 = right - 1;
	right = x_24;
	left = 0;
	var_cont = 1;
	goto L_28;
L_28:
	if (var_cont)
	  goto L_26;
	else
	  goto L_27;
L_26:
	x_25 = left + right;
	medium = x_25;
	x_26 = this->vptr->BS_Div(this, medium);
	medium = x_26;
	aux01 = (this->number + 4)[medium];
	x_27 = num < aux01;
	if (x_27)
	  goto L_29;
	else
	  goto L_30;
L_29:
	x_28 = medium - 1;
	right = x_28;
	goto L_31;
L_30:
	x_29 = medium + 1;
	left = x_29;
	goto L_31;
L_31:
	x_30 = this->vptr->BS_Compare(this, aux01, num);
	if (x_30)
	  goto L_32;
	else
	  goto L_33;
L_32:
	var_cont = 0;
	goto L_34;
L_33:
	var_cont = 1;
	goto L_34;
L_34:
	x_31 = right < left;
	if (x_31)
	  goto L_35;
	else
	  goto L_36;
L_35:
	var_cont = 0;
	goto L_37;
L_36:
	goto L_37;
L_37:
	goto L_28;
L_27:
	x_32 = this->vptr->BS_Compare(this, aux01, num);
	if (x_32)
	  goto L_38;
	else
	  goto L_39;
L_38:
	bs01 = 1;
	goto L_40;
L_39:
	bs01 = 0;
	goto L_40;
L_40:
	frame_prev = frame.frame_prev;
	return bs01;
}

struct BS_Div_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int BS_Div(struct BS * this, int num)
{
	int count01;
	int count02;
	int aux03;
	int x_33;
	int x_34;
	int x_35;
	int x_36;

	char * BS_Div_arguments_gc_map = "10";
	char * BS_Div_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct BS_Div_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BS_Div_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BS_Div_locals_gc_map;

L_41:

	count01 = 0;
	count02 = 0;
	x_33 = num - 1;
	aux03 = x_33;
	goto L_44;
L_44:
	x_34 = count02 < aux03;
	if (x_34)
	  goto L_42;
	else
	  goto L_43;
L_42:
	x_35 = count01 + 1;
	count01 = x_35;
	x_36 = count02 + 2;
	count02 = x_36;
	goto L_44;
L_43:
	frame_prev = frame.frame_prev;
	return count01;
}

struct BS_Compare_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int BS_Compare(struct BS * this, int num1, int num2)
{
	int retval;
	int aux02;
	int x_37;
	int x_38;
	int x_39;

	char * BS_Compare_arguments_gc_map = "100";
	char * BS_Compare_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct BS_Compare_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BS_Compare_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BS_Compare_locals_gc_map;

L_45:


	x_37 = num2 + 1;
	aux02 = x_37;
	x_38 = num1 < num2;
	if (x_38)
	  goto L_46;
	else
	  goto L_47;
L_46:
	retval = 0;
	goto L_48;
L_47:
	x_39 = num1 < aux02;
	if (!x_39)
	  goto L_49;
	else
	  goto L_50;
L_49:
	retval = 0;
	goto L_51;
L_50:
	retval = 1;
	goto L_51;
L_51:
	goto L_48;
L_48:
	frame_prev = frame.frame_prev;
	return retval;
}

struct BS_Print_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int BS_Print(struct BS * this)
{
	int j;
	int x_40;
	int x_41;

	char * BS_Print_arguments_gc_map = "1";
	char * BS_Print_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct BS_Print_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BS_Print_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BS_Print_locals_gc_map;

L_52:
	j = 1;
	goto L_55;
L_55:
	x_40 = j < this->size;
	if (x_40)
	  goto L_53;
	else
	  goto L_54;
L_53:
	System_out_println ((this->number + 4)[j]);

	x_41 = j + 1;
	j = x_41;
	goto L_55;
L_54:
	System_out_println (99999);

	frame_prev = frame.frame_prev;
	return 0;
}

struct BS_Init_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	int * x_42;
	int * x_43;
	int * x_44;
	int * x_45;
	int * x_46;
	int * x_47;
	int * x_48;
	int * x_49;
	int * x_50;
	int * x_51;
	int * x_52;
	int * x_53;
	int * x_54;
	int * x_55;
	int * x_56;
	int * x_57;
	int * x_58;
	int * x_59;
	int * x_60;
	int * x_61;
	int * x_62;
	int * x_63;
	int * x_64;
	int * x_65;
	int * x_66;
	int * x_67;
	int * x_68;
	int * x_69;
	int * x_70;
	int * x_71;
	int * x_72;
	int * x_73;
	int * x_74;
	int * x_75;
	int * x_76;
	int * x_77;
	int * x_78;
	int * x_79;
	int * x_80;
	int * x_81;
};

int BS_Init(struct BS * this, int sz)
{
	int j;
	int k;
	int aux02;
	int aux01;
	int * x_42;
	int * x_43;
	int * x_44;
	int * x_45;
	int * x_46;
	int * x_47;
	int * x_48;
	int * x_49;
	int * x_50;
	int * x_51;
	int * x_52;
	int * x_53;
	int * x_54;
	int * x_55;
	int * x_56;
	int * x_57;
	int * x_58;
	int * x_59;
	int * x_60;
	int * x_61;
	int * x_62;
	int * x_63;
	int * x_64;
	int * x_65;
	int * x_66;
	int * x_67;
	int * x_68;
	int * x_69;
	int * x_70;
	int * x_71;
	int * x_72;
	int * x_73;
	int * x_74;
	int * x_75;
	int * x_76;
	int * x_77;
	int * x_78;
	int * x_79;
	int * x_80;
	int * x_81;
	int x_82;
	int x_83;
	int x_84;
	int x_85;
	int x_86;
	int x_87;
	int x_88;

	char * BS_Init_arguments_gc_map = "10";
	char * BS_Init_locals_gc_map = "1111111111111111111111111111111111111111";
	//put the GC stack frame onto the call stack.
	struct BS_Init_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = BS_Init_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = BS_Init_locals_gc_map;

L_56:

	this->size = sz;
	x_42 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_42;
	x_43 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_43;
	x_44 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_44;
	x_45 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_45;
	x_46 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_46;
	x_47 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_47;
	x_48 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_48;
	x_49 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_49;
	x_50 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_50;
	x_51 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_51;
	x_52 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_52;
	x_53 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_53;
	x_54 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_54;
	x_55 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_55;
	x_56 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_56;
	x_57 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_57;
	x_58 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_58;
	x_59 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_59;
	x_60 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_60;
	x_61 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_61;
	x_62 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_62;
	x_63 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_63;
	x_64 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_64;
	x_65 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_65;
	x_66 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_66;
	x_67 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_67;
	x_68 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_68;
	x_69 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_69;
	x_70 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_70;
	x_71 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_71;
	x_72 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_72;
	x_73 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_73;
	x_74 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_74;
	x_75 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_75;
	x_76 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_76;
	x_77 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_77;
	x_78 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_78;
	x_79 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_79;
	x_80 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_80;
	x_81 = (int *)Tiger_new_array(sizeof(int) * sz);
	this->number = x_81;
	j = 1;
	x_82 = this->size + 1;
	k = x_82;
	goto L_59;
L_59:
	x_83 = j < this->size;
	if (x_83)
	  goto L_57;
	else
	  goto L_58;
L_57:
	x_84 = j + j;
	aux01 = x_84;
	x_85 = k - 3;
	aux02 = x_85;
	x_86 = aux01 + aux02;
	(this->number + 4)[j] = x_86;
	x_87 = j + 1;
	j = x_87;
	x_88 = k - 1;
	k = x_88;
	goto L_59;
L_58:
	frame_prev = frame.frame_prev;
	return 0;
}

// vtables
struct BinarySearch_vtable BinarySearch_vtable_ = 
{
	"",
};

struct BS_vtable BS_vtable_ = 
{
	"10",
	BS_Start,
	BS_Search,
	BS_Div,
	BS_Compare,
	BS_Print,
	BS_Init,
};


// main method

struct Tiger_main_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct BS * x_0;
	struct BS * x_90;
};

int Tiger_main ()
{
	int x_89;
	char * tiger_main_arguments_gc_map = "";
	char * tiger_main_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tiger_main_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = tiger_main_arguments_gc_map;
	frame.locals_gc_map = tiger_main_locals_gc_map;

L_60:
	frame.x_90 = ((struct BS*)(Tiger_new (&BS_vtable_, sizeof(struct BS))));
	x_89 = frame.x_90->vptr->BS_Start(frame.x_90, 20);
	System_out_println (x_89);

	frame_prev = frame.frame_prev;
	return 0;
}




