// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct Monster
{
	struct Monster_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct Foo
{
	struct Foo_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
// vtables structures
struct Monster_vtable
{
	char * Monster_gc_map;
};

struct Foo_vtable
{
	char * Foo_gc_map;
	int (*Foo_foo)();
};


// vtables defines
struct Monster_vtable Monster_vtable_ ;
struct Foo_vtable Foo_vtable_ ;

// methods
void * frame_prev;

struct Foo_foo_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Foo_foo(struct Foo * this)
{
	int sum;
	int x_1;
	int x_2;
	int x_3;
	int x_4;
	int x_5;
	int x_6;
	int x_7;
	int x_8;
	int x_9;
	int x_10;
	int x_11;
	int x_12;
	int x_13;
	int x_14;
	int x_15;
	int x_16;
	int x_17;
	int x_18;
	int x_19;
	int x_20;
	int x_21;
	int x_22;
	int x_23;
	int x_24;
	int x_25;
	int x_26;
	int x_27;
	int x_28;
	int x_29;
	int x_30;
	int x_31;
	int x_32;
	int x_33;
	int x_34;
	int x_35;
	int x_36;
	int x_37;
	int x_38;
	int x_39;
	int x_40;
	int x_41;
	int x_42;
	int x_43;
	int x_44;
	int x_45;
	int x_46;
	int x_47;
	int x_48;
	int x_49;
	int x_50;
	int x_51;
	int x_52;
	int x_53;
	int x_54;
	int x_55;
	int x_56;
	int x_57;
	int x_58;
	int x_59;
	int x_60;
	int x_61;
	int x_62;
	int x_63;
	int x_64;

	char * Foo_foo_arguments_gc_map = "1";
	char * Foo_foo_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Foo_foo_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Foo_foo_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Foo_foo_locals_gc_map;

L_0:
	sum = 64;
	frame_prev = frame.frame_prev;
	return sum;
}

// vtables
struct Monster_vtable Monster_vtable_ = 
{
	"",
};

struct Foo_vtable Foo_vtable_ = 
{
	"",
	Foo_foo,
};


// main method

struct Tiger_main_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Foo * x_0;
	struct Foo * x_66;
};

int Tiger_main ()
{
	int x_65;
	char * tiger_main_arguments_gc_map = "";
	char * tiger_main_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tiger_main_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = tiger_main_arguments_gc_map;
	frame.locals_gc_map = tiger_main_locals_gc_map;

L_1:
	frame.x_66 = ((struct Foo*)(Tiger_new (&Foo_vtable_, sizeof(struct Foo))));
	x_65 = frame.x_66->vptr->Foo_foo(frame.x_66);
	System_out_println (x_65);

	frame_prev = frame.frame_prev;
	return 0;
}




