// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct TreeVisitor
{
	struct TreeVisitor_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct TV
{
	struct TV_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
};
struct Tree
{
	struct Tree_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
	struct Tree * left;
	struct Tree * right;
	int key;
	int has_left;
	int has_right;
	struct Tree * my_null;
};
struct Visitor
{
	struct Visitor_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
	struct Tree * l;
	struct Tree * r;
};
struct MyVisitor
{
	struct MyVisitor_vtable *vptr;
	int isObjOrArray;
	unsigned length;
	void * forwarding;
	struct Tree * l;
	struct Tree * r;
};
// vtables structures
struct TreeVisitor_vtable
{
	char * TreeVisitor_gc_map;
};

struct TV_vtable
{
	char * TV_gc_map;
	int (*TV_Start)();
};

struct Tree_vtable
{
	char * Tree_gc_map;
	int (*Tree_Init)();
	int (*Tree_SetRight)();
	int (*Tree_SetLeft)();
	struct Tree * (*Tree_GetRight)();
	struct Tree * (*Tree_GetLeft)();
	int (*Tree_GetKey)();
	int (*Tree_SetKey)();
	int (*Tree_GetHas_Right)();
	int (*Tree_GetHas_Left)();
	int (*Tree_SetHas_Left)();
	int (*Tree_SetHas_Right)();
	int (*Tree_Compare)();
	int (*Tree_Insert)();
	int (*Tree_Delete)();
	int (*Tree_Remove)();
	int (*Tree_RemoveRight)();
	int (*Tree_RemoveLeft)();
	int (*Tree_Search)();
	int (*Tree_Print)();
	int (*Tree_RecPrint)();
	int (*Tree_accept)();
};

struct Visitor_vtable
{
	char * Visitor_gc_map;
	int (*Visitor_visit)();
};

struct MyVisitor_vtable
{
	char * MyVisitor_gc_map;
	int (*MyVisitor_visit)();
};


// vtables defines
struct TreeVisitor_vtable TreeVisitor_vtable_ ;
struct TV_vtable TV_vtable_ ;
struct Tree_vtable Tree_vtable_ ;
struct Visitor_vtable Visitor_vtable_ ;
struct MyVisitor_vtable MyVisitor_vtable_ ;

// methods
void * frame_prev;

struct TV_Start_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * root;
	struct MyVisitor * v;
	struct Tree * x_1;
	struct Tree * x_2;
	struct Tree * x_3;
	struct Tree * x_4;
	struct Tree * x_5;
	struct Tree * x_6;
	struct Tree * x_7;
	struct Tree * x_8;
	struct Tree * x_9;
	struct Tree * x_10;
	struct Tree * x_11;
	struct Tree * x_12;
	struct Tree * x_13;
	struct Tree * x_14;
	struct Tree * x_15;
	struct Tree * x_16;
	struct Tree * x_17;
	struct Tree * x_18;
	struct Tree * x_19;
	struct Tree * x_98;
	struct MyVisitor * x_109;
};

int TV_Start(struct TV * this)
{
	int ntb;
	int nti;
	int x_99;
	int x_100;
	int x_101;
	int x_102;
	int x_103;
	int x_104;
	int x_105;
	int x_106;
	int x_107;
	int x_108;
	int x_110;
	int x_111;
	int x_112;
	int x_113;
	int x_114;
	int x_115;
	int x_116;
	int x_117;
	int x_118;

	char * TV_Start_arguments_gc_map = "1";
	char * TV_Start_locals_gc_map = "11111111111111111111111";
	//put the GC stack frame onto the call stack.
	struct TV_Start_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = TV_Start_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = TV_Start_locals_gc_map;

L_0:
	frame.x_98 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.root = frame.x_98;
	x_99 = frame.root->vptr->Tree_Init(frame.root, 16);
	x_100 = frame.root->vptr->Tree_Print(frame.root);
	System_out_println (100000000);

	x_101 = frame.root->vptr->Tree_Insert(frame.root, 8);
	x_102 = frame.root->vptr->Tree_Insert(frame.root, 24);
	x_103 = frame.root->vptr->Tree_Insert(frame.root, 4);
	x_104 = frame.root->vptr->Tree_Insert(frame.root, 12);
	x_105 = frame.root->vptr->Tree_Insert(frame.root, 20);
	x_106 = frame.root->vptr->Tree_Insert(frame.root, 28);
	x_107 = frame.root->vptr->Tree_Insert(frame.root, 14);
	x_108 = frame.root->vptr->Tree_Print(frame.root);
	System_out_println (100000000);

	frame.x_109 = ((struct MyVisitor*)(Tiger_new (&MyVisitor_vtable_, sizeof(struct MyVisitor))));
	frame.v = frame.x_109;
	System_out_println (50000000);

	x_110 = frame.root->vptr->Tree_accept(frame.root, frame.v);
	System_out_println (100000000);

	x_111 = frame.root->vptr->Tree_Search(frame.root, 24);
	System_out_println (x_111);

	x_112 = frame.root->vptr->Tree_Search(frame.root, 12);
	System_out_println (x_112);

	x_113 = frame.root->vptr->Tree_Search(frame.root, 16);
	System_out_println (x_113);

	x_114 = frame.root->vptr->Tree_Search(frame.root, 50);
	System_out_println (x_114);

	x_115 = frame.root->vptr->Tree_Search(frame.root, 12);
	System_out_println (x_115);

	x_116 = frame.root->vptr->Tree_Delete(frame.root, 12);
	x_117 = frame.root->vptr->Tree_Print(frame.root);
	x_118 = frame.root->vptr->Tree_Search(frame.root, 12);
	System_out_println (x_118);

	frame_prev = frame.frame_prev;
	return 0;
}

struct Tree_Init_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_Init(struct Tree * this, int v_key)
{

	char * Tree_Init_arguments_gc_map = "10";
	char * Tree_Init_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_Init_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Init_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Init_locals_gc_map;

L_1:

	this->key = v_key;
	this->has_left = 0;
	this->has_right = 0;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_SetRight_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetRight(struct Tree * this, struct Tree * rn)
{

	char * Tree_SetRight_arguments_gc_map = "11";
	char * Tree_SetRight_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetRight_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetRight_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetRight_locals_gc_map;

L_2:

	this->right = rn;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_SetLeft_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetLeft(struct Tree * this, struct Tree * ln)
{

	char * Tree_SetLeft_arguments_gc_map = "11";
	char * Tree_SetLeft_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetLeft_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetLeft_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetLeft_locals_gc_map;

L_3:

	this->left = ln;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_GetRight_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

struct Tree * Tree_GetRight(struct Tree * this)
{

	char * Tree_GetRight_arguments_gc_map = "1";
	char * Tree_GetRight_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetRight_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetRight_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetRight_locals_gc_map;

L_4:
	frame_prev = frame.frame_prev;
	return this->right;
}

struct Tree_GetLeft_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

struct Tree * Tree_GetLeft(struct Tree * this)
{

	char * Tree_GetLeft_arguments_gc_map = "1";
	char * Tree_GetLeft_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetLeft_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetLeft_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetLeft_locals_gc_map;

L_5:
	frame_prev = frame.frame_prev;
	return this->left;
}

struct Tree_GetKey_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_GetKey(struct Tree * this)
{

	char * Tree_GetKey_arguments_gc_map = "1";
	char * Tree_GetKey_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetKey_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetKey_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetKey_locals_gc_map;

L_6:
	frame_prev = frame.frame_prev;
	return this->key;
}

struct Tree_SetKey_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetKey(struct Tree * this, int v_key)
{

	char * Tree_SetKey_arguments_gc_map = "10";
	char * Tree_SetKey_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetKey_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetKey_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetKey_locals_gc_map;

L_7:

	this->key = v_key;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_GetHas_Right_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_GetHas_Right(struct Tree * this)
{

	char * Tree_GetHas_Right_arguments_gc_map = "1";
	char * Tree_GetHas_Right_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetHas_Right_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetHas_Right_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetHas_Right_locals_gc_map;

L_8:
	frame_prev = frame.frame_prev;
	return this->has_right;
}

struct Tree_GetHas_Left_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_GetHas_Left(struct Tree * this)
{

	char * Tree_GetHas_Left_arguments_gc_map = "1";
	char * Tree_GetHas_Left_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_GetHas_Left_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_GetHas_Left_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_GetHas_Left_locals_gc_map;

L_9:
	frame_prev = frame.frame_prev;
	return this->has_left;
}

struct Tree_SetHas_Left_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetHas_Left(struct Tree * this, int val)
{

	char * Tree_SetHas_Left_arguments_gc_map = "10";
	char * Tree_SetHas_Left_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetHas_Left_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetHas_Left_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetHas_Left_locals_gc_map;

L_10:

	this->has_left = val;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_SetHas_Right_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_SetHas_Right(struct Tree * this, int val)
{

	char * Tree_SetHas_Right_arguments_gc_map = "10";
	char * Tree_SetHas_Right_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_SetHas_Right_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_SetHas_Right_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_SetHas_Right_locals_gc_map;

L_11:

	this->has_right = val;
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_Compare_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
};

int Tree_Compare(struct Tree * this, int num1, int num2)
{
	int ntb;
	int nti;
	int x_119;
	int x_120;
	int x_121;

	char * Tree_Compare_arguments_gc_map = "100";
	char * Tree_Compare_locals_gc_map = "";
	//put the GC stack frame onto the call stack.
	struct Tree_Compare_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Compare_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Compare_locals_gc_map;

L_12:


	x_119 = num2 + 1;
	nti = x_119;
	x_120 = num1 < num2;
	if (x_120)
	  goto L_13;
	else
	  goto L_14;
L_13:
	ntb = 0;
	goto L_15;
L_14:
	x_121 = num1 < nti;
	if (!x_121)
	  goto L_16;
	else
	  goto L_17;
L_16:
	ntb = 0;
	goto L_18;
L_17:
	ntb = 1;
	goto L_18;
L_18:
	goto L_15;
L_15:
	frame_prev = frame.frame_prev;
	return ntb;
}

struct Tree_Insert_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * new_node;
	struct Tree * current_node;
	struct Tree * x_20;
	struct Tree * x_21;
	struct Tree * x_22;
	struct Tree * x_23;
	struct Tree * x_24;
	struct Tree * x_25;
	struct Tree * x_26;
	struct Tree * x_27;
	struct Tree * x_28;
	struct Tree * x_29;
	struct Tree * x_122;
	struct Tree * x_127;
	struct Tree * x_131;
};

int Tree_Insert(struct Tree * this, int v_key)
{
	int ntb;
	int cont;
	int key_aux;
	int x_123;
	int x_124;
	int x_125;
	int x_126;
	int x_128;
	int x_129;
	int x_130;
	int x_132;
	int x_133;

	char * Tree_Insert_arguments_gc_map = "10";
	char * Tree_Insert_locals_gc_map = "111111111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Insert_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Insert_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Insert_locals_gc_map;

L_19:


	frame.x_122 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.new_node = frame.x_122;
	x_123 = frame.new_node->vptr->Tree_Init(frame.new_node, v_key);
	frame.current_node = this;
	cont = 1;
	goto L_22;
L_22:
	if (cont)
	  goto L_20;
	else
	  goto L_21;
L_20:
	x_124 = frame.current_node->vptr->Tree_GetKey(frame.current_node);
	key_aux = x_124;
	x_125 = v_key < key_aux;
	if (x_125)
	  goto L_23;
	else
	  goto L_24;
L_23:
	x_126 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	if (x_126)
	  goto L_26;
	else
	  goto L_27;
L_26:
	frame.x_127 = frame.current_node->vptr->Tree_GetLeft(frame.current_node);
	frame.current_node = frame.x_127;
	goto L_28;
L_27:
	cont = 0;
	x_128 = frame.current_node->vptr->Tree_SetHas_Left(frame.current_node, 1);
	x_129 = frame.current_node->vptr->Tree_SetLeft(frame.current_node, frame.new_node);
	goto L_28;
L_28:
	goto L_25;
L_24:
	x_130 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	if (x_130)
	  goto L_29;
	else
	  goto L_30;
L_29:
	frame.x_131 = frame.current_node->vptr->Tree_GetRight(frame.current_node);
	frame.current_node = frame.x_131;
	goto L_31;
L_30:
	cont = 0;
	x_132 = frame.current_node->vptr->Tree_SetHas_Right(frame.current_node, 1);
	x_133 = frame.current_node->vptr->Tree_SetRight(frame.current_node, frame.new_node);
	goto L_31;
L_31:
	goto L_25;
L_25:
	goto L_22;
L_21:
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_Delete_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * current_node;
	struct Tree * parent_node;
	struct Tree * x_30;
	struct Tree * x_31;
	struct Tree * x_32;
	struct Tree * x_33;
	struct Tree * x_34;
	struct Tree * x_35;
	struct Tree * x_36;
	struct Tree * x_37;
	struct Tree * x_38;
	struct Tree * x_134;
	struct Tree * x_135;
	struct Tree * x_136;
	struct Tree * x_137;
	struct Tree * x_138;
	struct Tree * x_139;
	struct Tree * x_140;
	struct Tree * x_141;
	struct Tree * x_142;
	struct Tree * x_146;
	struct Tree * x_149;
};

int Tree_Delete(struct Tree * this, int v_key)
{
	int cont;
	int found;
	int ntb;
	int is_root;
	int key_aux;
	int x_143;
	int x_144;
	int x_145;
	int x_147;
	int x_148;
	int x_150;
	int x_151;
	int x_152;
	int x_153;
	int x_154;

	char * Tree_Delete_arguments_gc_map = "10";
	char * Tree_Delete_locals_gc_map = "1111111111111111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Delete_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Delete_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Delete_locals_gc_map;

L_32:


	frame.current_node = this;
	frame.x_134 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_135 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_136 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_137 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_138 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_139 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_140 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_141 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.x_142 = ((struct Tree*)(Tiger_new (&Tree_vtable_, sizeof(struct Tree))));
	frame.parent_node = this;
	cont = 1;
	found = 0;
	is_root = 1;
	goto L_35;
L_35:
	if (cont)
	  goto L_33;
	else
	  goto L_34;
L_33:
	x_143 = frame.current_node->vptr->Tree_GetKey(frame.current_node);
	key_aux = x_143;
	x_144 = v_key < key_aux;
	if (x_144)
	  goto L_36;
	else
	  goto L_37;
L_36:
	x_145 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	if (x_145)
	  goto L_39;
	else
	  goto L_40;
L_39:
	frame.parent_node = frame.current_node;
	frame.x_146 = frame.current_node->vptr->Tree_GetLeft(frame.current_node);
	frame.current_node = frame.x_146;
	goto L_41;
L_40:
	cont = 0;
	goto L_41;
L_41:
	goto L_38;
L_37:
	x_147 = key_aux < v_key;
	if (x_147)
	  goto L_42;
	else
	  goto L_43;
L_42:
	x_148 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	if (x_148)
	  goto L_45;
	else
	  goto L_46;
L_45:
	frame.parent_node = frame.current_node;
	frame.x_149 = frame.current_node->vptr->Tree_GetRight(frame.current_node);
	frame.current_node = frame.x_149;
	goto L_47;
L_46:
	cont = 0;
	goto L_47;
L_47:
	goto L_44;
L_43:
	if (is_root)
	  goto L_48;
	else
	  goto L_49;
L_48:
	x_151 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	x_152 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	x_150 = !x_151 && !x_152;
	if (x_150)
	  goto L_51;
	else
	  goto L_52;
L_51:
	goto L_53;
L_52:
	x_153 = this->vptr->Tree_Remove(this, frame.parent_node, frame.current_node);
	goto L_53;
L_53:
	goto L_50;
L_49:
	x_154 = this->vptr->Tree_Remove(this, frame.parent_node, frame.current_node);
	goto L_50;
L_50:
	found = 1;
	cont = 0;
	goto L_44;
L_44:
	goto L_38;
L_38:
	is_root = 0;
	goto L_35;
L_34:
	frame_prev = frame.frame_prev;
	return found;
}

struct Tree_Remove_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_39;
	struct Tree * x_40;
	struct Tree * x_41;
	struct Tree * x_42;
	struct Tree * x_43;
	struct Tree * x_44;
	struct Tree * x_45;
	struct Tree * x_46;
	struct Tree * x_47;
	struct Tree * x_48;
	struct Tree * x_49;
	struct Tree * x_50;
	struct Tree * x_161;
};

int Tree_Remove(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
	int ntb;
	int auxkey1;
	int auxkey2;
	int x_155;
	int x_156;
	int x_157;
	int x_158;
	int x_159;
	int x_160;
	int x_162;
	int x_163;
	int x_164;
	int x_165;
	int x_166;

	char * Tree_Remove_arguments_gc_map = "111";
	char * Tree_Remove_locals_gc_map = "1111111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Remove_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Remove_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Remove_locals_gc_map;

L_54:



	x_155 = c_node->vptr->Tree_GetHas_Left(c_node);
	if (x_155)
	  goto L_55;
	else
	  goto L_56;
L_55:
	x_156 = this->vptr->Tree_RemoveLeft(this, p_node, c_node);
	goto L_57;
L_56:
	x_157 = c_node->vptr->Tree_GetHas_Right(c_node);
	if (x_157)
	  goto L_58;
	else
	  goto L_59;
L_58:
	x_158 = this->vptr->Tree_RemoveRight(this, p_node, c_node);
	goto L_60;
L_59:
	x_159 = c_node->vptr->Tree_GetKey(c_node);
	auxkey1 = x_159;
	frame.x_161 = p_node->vptr->Tree_GetLeft(p_node);
	x_160 = frame.x_161->vptr->Tree_GetKey(frame.x_161);
	auxkey2 = x_160;
	x_162 = this->vptr->Tree_Compare(this, auxkey1, auxkey2);
	if (x_162)
	  goto L_61;
	else
	  goto L_62;
L_61:
	x_163 = p_node->vptr->Tree_SetLeft(p_node, this->my_null);
	x_164 = p_node->vptr->Tree_SetHas_Left(p_node, 0);
	goto L_63;
L_62:
	x_165 = p_node->vptr->Tree_SetRight(p_node, this->my_null);
	x_166 = p_node->vptr->Tree_SetHas_Right(p_node, 0);
	goto L_63;
L_63:
	goto L_60;
L_60:
	goto L_57;
L_57:
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_RemoveRight_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_51;
	struct Tree * x_52;
	struct Tree * x_53;
	struct Tree * x_54;
	struct Tree * x_55;
	struct Tree * x_56;
	struct Tree * x_57;
	struct Tree * x_170;
	struct Tree * x_171;
};

int Tree_RemoveRight(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
	int ntb;
	int x_167;
	int x_168;
	int x_169;
	int x_172;
	int x_173;

	char * Tree_RemoveRight_arguments_gc_map = "111";
	char * Tree_RemoveRight_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_RemoveRight_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_RemoveRight_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_RemoveRight_locals_gc_map;

L_64:


	goto L_67;
L_67:
	x_167 = c_node->vptr->Tree_GetHas_Right(c_node);
	if (x_167)
	  goto L_65;
	else
	  goto L_66;
L_65:
	frame.x_170 = c_node->vptr->Tree_GetRight(c_node);
	x_169 = frame.x_170->vptr->Tree_GetKey(frame.x_170);
	x_168 = c_node->vptr->Tree_SetKey(c_node, x_169);
	p_node = c_node;
	frame.x_171 = c_node->vptr->Tree_GetRight(c_node);
	c_node = frame.x_171;
	goto L_67;
L_66:
	x_172 = p_node->vptr->Tree_SetRight(p_node, this->my_null);
	x_173 = p_node->vptr->Tree_SetHas_Right(p_node, 0);
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_RemoveLeft_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_58;
	struct Tree * x_59;
	struct Tree * x_60;
	struct Tree * x_61;
	struct Tree * x_62;
	struct Tree * x_63;
	struct Tree * x_64;
	struct Tree * x_177;
	struct Tree * x_178;
};

int Tree_RemoveLeft(struct Tree * this, struct Tree * p_node, struct Tree * c_node)
{
	int ntb;
	int x_174;
	int x_175;
	int x_176;
	int x_179;
	int x_180;

	char * Tree_RemoveLeft_arguments_gc_map = "111";
	char * Tree_RemoveLeft_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_RemoveLeft_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_RemoveLeft_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_RemoveLeft_locals_gc_map;

L_68:


	goto L_71;
L_71:
	x_174 = c_node->vptr->Tree_GetHas_Left(c_node);
	if (x_174)
	  goto L_69;
	else
	  goto L_70;
L_69:
	frame.x_177 = c_node->vptr->Tree_GetLeft(c_node);
	x_176 = frame.x_177->vptr->Tree_GetKey(frame.x_177);
	x_175 = c_node->vptr->Tree_SetKey(c_node, x_176);
	p_node = c_node;
	frame.x_178 = c_node->vptr->Tree_GetLeft(c_node);
	c_node = frame.x_178;
	goto L_71;
L_70:
	x_179 = p_node->vptr->Tree_SetLeft(p_node, this->my_null);
	x_180 = p_node->vptr->Tree_SetHas_Left(p_node, 0);
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_Search_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * current_node;
	struct Tree * x_65;
	struct Tree * x_66;
	struct Tree * x_67;
	struct Tree * x_68;
	struct Tree * x_69;
	struct Tree * x_184;
	struct Tree * x_187;
};

int Tree_Search(struct Tree * this, int v_key)
{
	int ifound;
	int cont;
	int key_aux;
	int x_181;
	int x_182;
	int x_183;
	int x_185;
	int x_186;

	char * Tree_Search_arguments_gc_map = "10";
	char * Tree_Search_locals_gc_map = "11111111";
	//put the GC stack frame onto the call stack.
	struct Tree_Search_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Search_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Search_locals_gc_map;

L_72:


	frame.current_node = this;
	cont = 1;
	ifound = 0;
	goto L_75;
L_75:
	if (cont)
	  goto L_73;
	else
	  goto L_74;
L_73:
	x_181 = frame.current_node->vptr->Tree_GetKey(frame.current_node);
	key_aux = x_181;
	x_182 = v_key < key_aux;
	if (x_182)
	  goto L_76;
	else
	  goto L_77;
L_76:
	x_183 = frame.current_node->vptr->Tree_GetHas_Left(frame.current_node);
	if (x_183)
	  goto L_79;
	else
	  goto L_80;
L_79:
	frame.x_184 = frame.current_node->vptr->Tree_GetLeft(frame.current_node);
	frame.current_node = frame.x_184;
	goto L_81;
L_80:
	cont = 0;
	goto L_81;
L_81:
	goto L_78;
L_77:
	x_185 = key_aux < v_key;
	if (x_185)
	  goto L_82;
	else
	  goto L_83;
L_82:
	x_186 = frame.current_node->vptr->Tree_GetHas_Right(frame.current_node);
	if (x_186)
	  goto L_85;
	else
	  goto L_86;
L_85:
	frame.x_187 = frame.current_node->vptr->Tree_GetRight(frame.current_node);
	frame.current_node = frame.x_187;
	goto L_87;
L_86:
	cont = 0;
	goto L_87;
L_87:
	goto L_84;
L_83:
	ifound = 1;
	cont = 0;
	goto L_84;
L_84:
	goto L_78;
L_78:
	goto L_75;
L_74:
	frame_prev = frame.frame_prev;
	return ifound;
}

struct Tree_Print_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * current_node;
	struct Tree * x_70;
};

int Tree_Print(struct Tree * this)
{
	int ntb;
	int x_188;

	char * Tree_Print_arguments_gc_map = "1";
	char * Tree_Print_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tree_Print_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_Print_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_Print_locals_gc_map;

L_88:

	frame.current_node = this;
	x_188 = this->vptr->Tree_RecPrint(this, frame.current_node);
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_RecPrint_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_71;
	struct Tree * x_72;
	struct Tree * x_73;
	struct Tree * x_74;
	struct Tree * x_75;
	struct Tree * x_76;
	struct Tree * x_77;
	struct Tree * x_191;
	struct Tree * x_195;
};

int Tree_RecPrint(struct Tree * this, struct Tree * node)
{
	int ntb;
	int x_189;
	int x_190;
	int x_192;
	int x_193;
	int x_194;

	char * Tree_RecPrint_arguments_gc_map = "11";
	char * Tree_RecPrint_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct Tree_RecPrint_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_RecPrint_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_RecPrint_locals_gc_map;

L_89:


	x_189 = node->vptr->Tree_GetHas_Left(node);
	if (x_189)
	  goto L_90;
	else
	  goto L_91;
L_90:
	frame.x_191 = node->vptr->Tree_GetLeft(node);
	x_190 = this->vptr->Tree_RecPrint(this, frame.x_191);
	goto L_92;
L_91:
	goto L_92;
L_92:
	x_192 = node->vptr->Tree_GetKey(node);
	System_out_println (x_192);

	x_193 = node->vptr->Tree_GetHas_Right(node);
	if (x_193)
	  goto L_93;
	else
	  goto L_94;
L_93:
	frame.x_195 = node->vptr->Tree_GetRight(node);
	x_194 = this->vptr->Tree_RecPrint(this, frame.x_195);
	goto L_95;
L_94:
	goto L_95;
L_95:
	frame_prev = frame.frame_prev;
	return 1;
}

struct Tree_accept_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Visitor * x_78;
};

int Tree_accept(struct Tree * this, struct Visitor * v)
{
	int nti;
	int x_196;

	char * Tree_accept_arguments_gc_map = "11";
	char * Tree_accept_locals_gc_map = "1";
	//put the GC stack frame onto the call stack.
	struct Tree_accept_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Tree_accept_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Tree_accept_locals_gc_map;

L_96:


	System_out_println (333);

	x_196 = v->vptr->Visitor_visit(v, this);
	frame_prev = frame.frame_prev;
	return 0;
}

struct Visitor_visit_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_79;
	struct Tree * x_80;
	struct Tree * x_81;
	struct Tree * x_82;
	struct Tree * x_83;
	struct Tree * x_84;
	struct Tree * x_198;
	struct Tree * x_201;
};

int Visitor_visit(struct Visitor * this, struct Tree * n)
{
	int nti;
	int x_197;
	int x_199;
	int x_200;
	int x_202;

	char * Visitor_visit_arguments_gc_map = "11";
	char * Visitor_visit_locals_gc_map = "11111111";
	//put the GC stack frame onto the call stack.
	struct Visitor_visit_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = Visitor_visit_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = Visitor_visit_locals_gc_map;

L_97:


	x_197 = n->vptr->Tree_GetHas_Right(n);
	if (x_197)
	  goto L_98;
	else
	  goto L_99;
L_98:
	frame.x_198 = n->vptr->Tree_GetRight(n);
	this->r = frame.x_198;
	x_199 = this->r->vptr->Tree_accept(this->r, this);
	goto L_100;
L_99:
	goto L_100;
L_100:
	x_200 = n->vptr->Tree_GetHas_Left(n);
	if (x_200)
	  goto L_101;
	else
	  goto L_102;
L_101:
	frame.x_201 = n->vptr->Tree_GetLeft(n);
	this->l = frame.x_201;
	x_202 = this->l->vptr->Tree_accept(this->l, this);
	goto L_103;
L_102:
	goto L_103;
L_103:
	frame_prev = frame.frame_prev;
	return 0;
}

struct MyVisitor_visit_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct Tree * x_91;
	struct Tree * x_92;
	struct Tree * x_93;
	struct Tree * x_94;
	struct Tree * x_95;
	struct Tree * x_96;
	struct Tree * x_97;
	struct Tree * x_204;
	struct Tree * x_208;
};

int MyVisitor_visit(struct MyVisitor * this, struct Tree * n)
{
	int nti;
	int x_203;
	int x_205;
	int x_206;
	int x_207;
	int x_209;

	char * MyVisitor_visit_arguments_gc_map = "11";
	char * MyVisitor_visit_locals_gc_map = "111111111";
	//put the GC stack frame onto the call stack.
	struct MyVisitor_visit_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = MyVisitor_visit_arguments_gc_map;
	frame.arguments_base_address = (int *)&this;
	frame.locals_gc_map = MyVisitor_visit_locals_gc_map;

L_104:


	x_203 = n->vptr->Tree_GetHas_Right(n);
	if (x_203)
	  goto L_105;
	else
	  goto L_106;
L_105:
	frame.x_204 = n->vptr->Tree_GetRight(n);
	this->r = frame.x_204;
	x_205 = this->r->vptr->Tree_accept(this->r, this);
	goto L_107;
L_106:
	goto L_107;
L_107:
	x_206 = n->vptr->Tree_GetKey(n);
	System_out_println (x_206);

	x_207 = n->vptr->Tree_GetHas_Left(n);
	if (x_207)
	  goto L_108;
	else
	  goto L_109;
L_108:
	frame.x_208 = n->vptr->Tree_GetLeft(n);
	this->l = frame.x_208;
	x_209 = this->l->vptr->Tree_accept(this->l, this);
	goto L_110;
L_109:
	goto L_110;
L_110:
	frame_prev = frame.frame_prev;
	return 0;
}

// vtables
struct TreeVisitor_vtable TreeVisitor_vtable_ = 
{
	"",
};

struct TV_vtable TV_vtable_ = 
{
	"",
	TV_Start,
};

struct Tree_vtable Tree_vtable_ = 
{
	"110001",
	Tree_Init,
	Tree_SetRight,
	Tree_SetLeft,
	Tree_GetRight,
	Tree_GetLeft,
	Tree_GetKey,
	Tree_SetKey,
	Tree_GetHas_Right,
	Tree_GetHas_Left,
	Tree_SetHas_Left,
	Tree_SetHas_Right,
	Tree_Compare,
	Tree_Insert,
	Tree_Delete,
	Tree_Remove,
	Tree_RemoveRight,
	Tree_RemoveLeft,
	Tree_Search,
	Tree_Print,
	Tree_RecPrint,
	Tree_accept,
};

struct Visitor_vtable Visitor_vtable_ = 
{
	"11",
	Visitor_visit,
};

struct MyVisitor_vtable MyVisitor_vtable_ = 
{
	"11",
	MyVisitor_visit,
};


// main method

struct Tiger_main_gc_frame{
	void * frame_prev;
	int * arguments_base_address;
	char * arguments_gc_map;
	char * locals_gc_map;
	struct TV * x_0;
	struct TV * x_211;
};

int Tiger_main ()
{
	int x_210;
	char * tiger_main_arguments_gc_map = "";
	char * tiger_main_locals_gc_map = "11";
	//put the GC stack frame onto the call stack.
	struct Tiger_main_gc_frame frame;
	//push this frame onto the GC stack by setting up "prev".
	frame.frame_prev = frame_prev;
	frame_prev = &frame;
	//setting up memory GC maps and corresponding base addresses
	frame.arguments_gc_map = tiger_main_arguments_gc_map;
	frame.locals_gc_map = tiger_main_locals_gc_map;

L_111:
	frame.x_211 = ((struct TV*)(Tiger_new (&TV_vtable_, sizeof(struct TV))));
	x_210 = frame.x_211->vptr->TV_Start(frame.x_211);
	System_out_println (x_210);

	frame_prev = frame.frame_prev;
	return 0;
}




